# 11-785 Recitation 0b: NumPy

$\hspace{5mm}$Omar Khattab - okhattab@cmu.edu

## Introduction

- What is NumPy?
- What is vectorization?
- Why vectorization?

## Download and Installation

Follow instructions at https://scipy.org/install.html

## Introductory Example: Wx + b

### Naive Python Implementation

In [ ]:
# Inputs
W = [[1, 1, 1],
     [2, 2, 2],
     [3, 3, 3]]

x = [7, 8, 5]
b = [1, 1, 1]

# Output
y = [0, 0, 0]

# Naive Computation of Wx + b
for i in range(len(W)):
    for j in range(len(x)):
        y[i] += W[i][j] * x[j]

for i in range(len(y)):
    y[i] += b[i]

y

### NumPy-based Vectorized Implementation

In [ ]:
import numpy as np

In [ ]:
W = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])
W

In [ ]:
x = np.array([7, 8, 5])
x

In [ ]:
b = np.ones(3)
b

In [ ]:
W.dot(x)

In [ ]:
W.dot(x) + b

## Multi-Dimensional Arrays

In [ ]:
T = np.random.random((2,3,4))
T

In [ ]:
W = T[1]
W.shape, W.dtype

In [ ]:
X = np.full((4,3), 11785, dtype=np.int32)
X.shape, X.dtype

In [ ]:
W.dot(X)

In [ ]:
X2 = np.zeros(X.shape)

np.array_equal(W.dot(X2), np.zeros((3,3)))

## Basic Element-wise Operations

In [ ]:
y = np.arange(10)
y, np.array(range(10))

In [ ]:
y == np.array(range(10))

In [ ]:
y + 1

In [ ]:
y * 10

In [ ]:
(y + 1)**2

In [ ]:
y + y

In [ ]:
y / (y + 1)

In [ ]:
np.sqrt(y**2)

In [ ]:
y.min(), y.max(), y.std(), y.sum()

## Indexing NumPy Arrays

In [ ]:
np.save('tensor.npy', np.arange(2 * 4 * 4).reshape(2, 4, 4))

In [ ]:
T = np.load('tensor.npy')
T,  T.shape

In [ ]:
T[0]

In [ ]:
T[1,0,0]  # more efficient version of T[1][0][0]

In [ ]:
T[0,1:3,0:2]

In [ ]:
(T % 10) == 0

In [ ]:
T[(T % 10) == 0]

## Example: Masking and Clipping

In [ ]:
W = np.random.randint(0, 10, (4, 4))
W

In [ ]:
mask = np.ones_like(W)
mask[1] = 0
mask

In [ ]:
W * mask

In [ ]:
W > 5

In [ ]:
W2 = W
W2[W2 > 5] = 5
W2

In [ ]:
np.minimum(W, 5)

## Computation Along Axes

In [ ]:
A = np.random.random((3,3))
A

In [ ]:
A.sum()

In [ ]:
A.sum(axis=0)

In [ ]:
A.sum(axis=1)

In [ ]:
A.max(axis=0), A.argmax(axis=0)

## Combining Arrays: Stacking & Concatenation

In [46]:
a = np.full(5, 1)
b = np.full(5, 2)
c = np.full(5, 3)
a, b, c

(array([1, 1, 1, 1, 1]), array([2, 2, 2, 2, 2]), array([3, 3, 3, 3, 3]))

Stacking creates a new axis. It joins the supplied arrays, which must have the same shape, along that axis.
Indexing a single element from that axis returns the appropriate input array.

In [47]:
B = np.stack([a, b, c], axis=1)
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (5, 3))

In [48]:
B[:,1]

array([2, 2, 2, 2, 2])

Concatenating arrays joins them along an *existing* aixs.

In [49]:
C = np.concatenate([B+100, B+200], axis=1)
C

array([[101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203]])

## Transposing and Reshaping

In [50]:
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (5, 3))

In [51]:
BT = B.T
BT, BT.shape

(array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]]), (3, 5))

In [52]:
BR = B.reshape(3, 5)
BR, BR.shape

(array([[1, 2, 3, 1, 2],
        [3, 1, 2, 3, 1],
        [2, 3, 1, 2, 3]]), (3, 5))

## Broadcasting

In [ ]:
A = np.random.random((8, 4))
B = np.random.random((4, 3))
A.dot(B)

In [ ]:
b = np.array([10, 20, 30])
A.dot(B) + b

Arrays must have same ending dimensions to broadcast.

In [ ]:
print(np.arange(12).reshape((3,4)) + 0.01 * np.arange(4))
print(np.arange(8).reshape((2,4)) + 0.01 * np.arange(24).reshape((3,2,4)))
print(np.arange(6).reshape((3,1,2)) + 0.01 * np.arange(18).reshape((3,3,2)))

Mismatched dimensions cause an error.

In [ ]:
try:
  x = np.random.random((3,3,4))+np.random.random((3,2,4))
except ValueError as e:
  print(e)

## Saving and Loading

### Saving and loading a single NumPy array

In [ ]:
# Save single array
x = np.random.random((5,))
print(x)

np.save('tmp.npy', x)

In [ ]:
# Load the array
y = np.load('tmp.npy')

print(y)

### Saving and loading a dictionary of NumPy arrays

In [ ]:
# Save dictionary of arrays
x1 = np.random.random((2,))
y1 = np.random.random((3,))
print(x1, y1)

np.savez('tmp.npz', x=x1, y=y1)

In [ ]:
# Load the dictionary of arrays
data = np.load('tmp.npz')

print(data['x'])
print(data['y'])

## References

You can find a more complete introduction at https://docs.scipy.org/doc/numpy/user/quickstart.html

The following links were helpful in preparing this notebook:

- https://docs.scipy.org/doc/numpy/reference/index.html
- https://github.com/cmudeeplearning11785/deep-learning-tutorials/blob/master/recitation-2/Tutorial-numpy.ipynb
- http://cs231n.github.io/python-numpy-tutorial/#numpy